[package]
name = "zig-up"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
inquire = "0.7.5"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde = { version = "1.0.204", features = ["derive"] }
simple-home-dir = "0.3.5"
tar = "0.4.41"
xz = "0.1.0"
