[package]
name = "zig-up"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
inquire = "0.7.5"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.38.1", features = ["full"] }
